// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Needed by `prisma db push` against PostgreSQL to introspect the
    // current schema. On Render this falls back to DATABASE_URL itself
    // (fine for an empty/fresh database). Local SQLite dev is unaffected.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
